"""Core data models, loaders, and rule/import utilities."""

from rime_core.annotation import (
    Annotation,
    AnnotationStore,
    ConfidenceType,
    ReviewLayer,
    RuleEngine,
    SideEffect,
    Violation,
    edit_annotation_label,
    generate_id,
    load_review_layer,
    split_annotation,
)
from rime_core.analysis import CoverageResult, CoverageSpec, EvalResult, IRRLabelResult, IRRResult
from rime_core.analysis import compute_coverage, compute_irr, evaluate_model
from rime_core.io import (
    BIDSSessionPaths,
    BidsSignalInput,
    ExportError,
    ExporterRegistry,
    ImportResult,
    TierMapping,
    auto_map_tiers,
    bids_session_paths,
    derive_matched_episode_interval,
    export_irr_report,
    export_bids_channels,
    export_bids_dataset,
    export_bids_events,
    export_bids_events_sidecar,
    export_bids_motion,
    export_bids_signal_clips,
    export_matched_episode_parquet,
    export_parquet,
    export_workspace_report,
    export_signal_clips,
    export_video_clips,
    extract_media_files,
    import_eaf,
    import_workspace_from_elan,
    load_csv_signal,
    normalize_label,
    sanitize_bids_entity_value,
    Signal,
    SignalLoaderError,
    SignalLoaderRegistry,
    detect_signal_config,
    write_bids_dataset_descriptions,
)
from rime_core.modeling import (
    CMFConfig,
    CMFLoader,
    CMFMissingRequirement,
    CMFPackage,
    CMFRequirement,
    CMFValidationError,
    InferenceError,
    InferenceResult,
    InferenceRunner,
    InputBinding,
    OutputMapping,
    OutputPredictions,
)
from rime_core.schema import (
    LaneSchema,
    ProtocolSchema,
    SchemaValidationError,
    suggest_next_schema_version,
)
from rime_core.settings import AppSettings, load_settings, save_settings
from rime_core.records import (
    AnnotationSet, CalculationTemplate, RecordingCatalog, ResearchContext, SignalSource, VideoSource,
)
from rime_core.workspace.models import ModelSettings, DEFAULT_PANEL_VISIBILITY, MAX_VIDEO_VIEWS
from rime_core.workspace import WorkingContext, WorkspaceSession

__all__ = [
    "AnnotationSet", "ResearchContext", "RecordingCatalog",
    "Annotation",
    "AnnotationStore",
    "ConfidenceType",
    "generate_id",
    "split_annotation",
    "edit_annotation_label",
    "CMFConfig",
    "CMFPackage",
    "CMFLoader",
    "CMFMissingRequirement",
    "CMFRequirement",
    "CMFValidationError",
    "CoverageSpec",
    "CoverageResult",
    "compute_coverage",
    "InferenceResult",
    "InferenceRunner",
    "InferenceError",
    "InputBinding",
    "OutputMapping",
    "OutputPredictions",
    "LaneSchema",
    "ProtocolSchema",
    "SignalLoaderRegistry",
    "SignalLoaderError",
    "SchemaValidationError",
    "suggest_next_schema_version",
    "AppSettings",
    "load_settings",
    "save_settings",
    "WorkingContext",
    "WorkspaceSession",
    "EvalResult",
    "evaluate_model",
    "IRRLabelResult",
    "IRRResult",
    "compute_irr",
    "ExporterRegistry",
    "ExportError",
    "BIDSSessionPaths",
    "BidsSignalInput",
    "bids_session_paths",
    "derive_matched_episode_interval",
    "export_bids_channels",
    "export_bids_dataset",
    "export_bids_events",
    "export_bids_events_sidecar",
    "export_bids_motion",
    "export_bids_signal_clips",
    "export_irr_report",
    "export_matched_episode_parquet",
    "export_parquet",
    "export_workspace_report",
    "export_signal_clips",
    "export_video_clips",
    "ReviewLayer",
    "load_review_layer",
    "RuleEngine",
    "SideEffect",
    "Violation",
    "TierMapping",
    "ImportResult",
    "auto_map_tiers",
    "normalize_label",
    "sanitize_bids_entity_value",
    "write_bids_dataset_descriptions",
    "extract_media_files",
    "import_eaf",
    "import_workspace_from_elan",
    "ModelSettings",
    "CalculationTemplate",
    "DEFAULT_PANEL_VISIBILITY",
    "MAX_VIDEO_VIEWS",
    "VideoSource",
    "SignalSource",
    "Signal",
    "detect_signal_config",
    "load_csv_signal",
]
