"""Optional publication projection of a complete record overlay.

Grouping changes display only. Members and edges always point back to the full
view; unknown markers and changed supporting dependencies remain inspectable.
"""

from copy import deepcopy
from html import escape

from .clinical_comparison import row_label
from .comparison_view import _label
from .record_overlay import _acyclic


def publication_view(overlay):
    nodes = {n["id"]: n for n in overlay["nodes"]}
    core = set(overlay["roots"].values())
    pending = list(core)
    while pending:
        owner = pending.pop()
        for edge in overlay["edges"]:
            main = edge["relation"] == "prov:wasGeneratedBy" or (
                edge["relation"] == "prov:used"
                and edge["role"]
                in (
                    "rime:annotations",
                    "rime:annotation_input",
                    "rime:observation",
                    "rime:definition",
                )
            )
            if edge["source"] == owner and main and edge["target"] not in core:
                core.add(edge["target"])
                pending.append(edge["target"])
    # A changed qualified use (e.g. source timing) must expand its endpoint even
    # when the underlying file node is shared. Never bury such a difference.
    protected = set()
    for n in nodes.values():
        for r in n["comparison"].get("relationships", []):
            if r["status"] in ("different", "only_a", "only_b"):
                protected.update(
                    k for k, target in nodes.items() if target["component"] == r["target_component"]
                )
    grouped = {
        k
        for k, n in nodes.items()
        if k not in core
        and k not in protected
        and n["sides"] == ["a", "b"]
        and n["status"] in ("shared", "equal", "unavailable")
    }

    def project(members):
        display = [
            dict(
                id=k,
                members=[k],
                sides=n["sides"],
                status=n["status"],
                unavailable=n["unavailable"],
                labels=labels(n),
                kind=kind(n),
            )
            for k, n in nodes.items()
            if k not in members
        ]
        if members:
            roles = sorted(
                {
                    e["role"].removeprefix("rime:").replace("_", " ")
                    for e in overlay["edges"]
                    if e["target"] in members and e["source"] not in members and e["role"]
                }
            )
            has_agent = any(kind(nodes[k]) == "agent" for k in members)
            text = ["Shared supporting inputs", " · ".join(roles)]
            if has_agent:
                text.append("Agents and files retained in details")
            unknown = any(nodes[k]["unavailable"] for k in members)
            if unknown:
                text.append("Some provenance unavailable")
            display.append(
                dict(
                    id="supporting",
                    members=sorted(members),
                    sides=["a", "b"],
                    status="group",
                    unavailable=unknown,
                    labels=text,
                    kind="support",
                )
            )
        edges = {}
        hidden = []
        for index, e in enumerate(overlay["edges"]):
            source = "supporting" if e["source"] in members else e["source"]
            target = "supporting" if e["target"] in members else e["target"]
            if source == target == "supporting":
                hidden.append(index)
                continue
            label = (
                "supporting dependencies"
                if "supporting" in (source, target)
                else {
                    "prov:used": "used",
                    "prov:wasGeneratedBy": "was generated by",
                    "prov:wasAssociatedWith": "was associated with",
                }[e["relation"]]
            )
            key = (source, target, label, tuple(e["sides"]))
            entry = edges.setdefault(
                key, dict(source=source, target=target, label=label, sides=e["sides"], members=[])
            )
            entry["members"].append(index)
        return dict(
            nodes=display,
            edges=list(edges.values()),
            hidden_edges=hidden,
            numerical_comparison=deepcopy(overlay["numerical_comparison"]),
        )

    result = project(grouped)
    if not _acyclic(result["nodes"], result["edges"]):
        result = project(set())
        result["grouping_warning"] = "Supporting inputs left expanded to preserve DAG structure."
    return result


def kind(n):
    raw = next(iter(n["originals"].values()))
    return (
        "activity"
        if "prov:Activity" in raw["@type"]
        else "agent"
        if "prov:Agent" in raw["@type"]
        else "entity"
    )


def labels(n):
    side = n["sides"][0]
    raw = n["originals"][side]
    if any(t in raw["@type"] for t in ("rime:AnnotationProduction", "rime:AnnotationReview")):
        text = row_label(dict(nodes=n["originals"], comparison=n["comparison"]), side)
    else:
        text = _label(raw, n["comparison"], side)
        if "rime:ObservationPeriod" in raw["@type"]:
            spans = raw["rime:data"]["intervals"]
            if len(spans) == 1:
                text[1] = f"{spans[0][0] / 1000:g}–{spans[0][1] / 1000:g} s"
    if n["status"] == "equal":
        text.append("A = B")
    if len(n["sides"]) == 1:
        text.insert(0, "Record " + side.upper())
    if n["unavailable"]:
        text.append("Provenance partly unavailable")
    return text


def to_mermaid(view):
    lines = ["flowchart TB", "  %% Display groups retain references to every full-overlay member."]
    for n in view["nodes"]:
        label = "<br/>".join(escape(str(x), quote=True) for x in n["labels"])
        lines += [f'  {n["id"]}["{label}"]', f"  class {n['id']} {n['kind']};"]
    for e in view["edges"]:
        label = e["label"] if len(e["sides"]) == 2 else e["sides"][0].upper() + " · " + e["label"]
        lines.append(f'  {e["source"]} -->|"{escape(label, quote=True)}"| {e["target"]}')
    for kind_, color in [
        ("entity", "#DBE8F4"),
        ("activity", "#F2D3CF"),
        ("agent", "#DCF0D4"),
        ("support", "#F4F4F4"),
    ]:
        lines.append(f"  classDef {kind_} fill:{color},stroke:#888,color:#111;")
    return "\n".join(lines) + "\n"
